### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by WH173-5P1D3R**
Add This API in to ragnarok-bot API package.json

### CODE REVIEW

**Comment by souravkl11** [comment]
Yes, it has!

**Comment by WH173-5P1D3R** [comment]
> Yes, it has! that's why I haven't merged #23

you already merged in textmaker.js go & check it

**Comment by souravkl11** [comment]
> > Yes, it has! that's why I haven't merged #23
> 
> you already merged in textmaker.js go & check it

Vro, I'm telling about #23 . not #22 🙂

**Comment by WH173-5P1D3R** [comment]
update 

"w5-textmaker": "^1.0.2"

**Pull request closed without merging**
